name: zerotier
summary: ZeroTier is a software-based managed Ethernet switch for planet Earth.
description: |
  It erases the LAN/WAN distinction and makes VPNs, tunnels, proxies, and other kludges arising from the inflexible nature of physical networks obsolete. Everything is encrypted end-to-end and traffic takes the most direct (peer to peer) path available.
  This snap contains ZeroTier One, a service that provides ZeroTier network connectivity and makes joining virtual networks as easy as joining IRC or Slack channels.
  Visit ZeroTier's site for more information and pre-built binary packages. Apps for Android and iOS are available for free in the Google Play and Apple app stores.
adopt-info: zerotier-one
confinement: strict
grade: stable
base: core20

apps:
  zerotier-one:
    # Add -U to prevent attempting to drop privileges since snaps have their
    # own containment mechanism. Otherwise, if a user named "zerotier-one"
    # exists on the system, the setgid or related calls will fail.
    command: usr/sbin/zerotier-one -U
    daemon: simple
    plugs:
      - network
      - network-bind
      - network-control

  zerotier-cli:
    command: usr/sbin/zerotier-cli
    plugs:
      - network

  zerotier-idtool:
    command: usr/sbin/zerotier-idtool
    plugs:
      - network

layout:
  /var/lib/zerotier-one:
    bind: $SNAP_COMMON

parts:
  zerotier-one:
    plugin: make
    source: https://github.com/zerotier/ZeroTierOne.git
    source-type: git
    build-packages:
      - build-essential
      - libc++-dev
    make-parameters:
      - CXX=g++
    filesets:
      binaries:
        - usr/sbin/zerotier-one
        - usr/sbin/zerotier-cli
        - usr/sbin/zerotier-idtool
    prime:
      - $binaries
    override-build: |
      snapcraftctl build
      # Grab the version string from the newly-compiled binary.
      snapcraftctl set-version "$(./zerotier-one -v)"
slots:
  zerotier-control:
    interface: content
    read:
      - $SNAP_COMMON
